/ekf_filter_node:
  ros__parameters:
    # [X,Y,Z,roll,pitch,yaw,X˙,Y˙,Z˙,roll˙,pitch˙,yaw˙,X¨,Y¨,Z¨]
    base_link_frame: base_link
    base_link_frame_output: base_link
    disabled_at_startup: false
    dynamic_process_noise_covariance: false
    frequency: 30.0
    history_length: 0.0
    imu0: /imu_data
    imu0_config: [false, false, false, 
                    true, true, true, 
                    false, false, false, 
                    true, true, true, 
                    true, true, true]

    map_frame: map
    odom0: /odom_raw
    odom0_config: [true,  true,  true,
                false, false, true,
                true, true, true,
                false, false, false,
                false, false, false]
    odom_frame: odom

    permit_corrected_publication: false

    predict_to_current_time: false
    print_diagnostics: false

    publish_acceleration: false
    publish_tf: true

    reset_on_time_jump: false
    sensor_timeout: 0.03333333333333333
    smooth_lagged_data: false

    two_d_mode: true
    use_control: false
    use_sim_time: false
    world_frame: odom